name: "Run checks on push"

on:
  push:
    paths: [ "**.png", "**.json", "**.gift" ]

jobs:
  compile-submod:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Check"
        uses: "friends-of-monika/spritepack-check-action@v1"
